#! /bin/sh

set -e

WWW_ROOT=/var/www/side-sup-interactive-survey-2024/build

case "$1" in
    configure)

      if [ -d $WWW_ROOT ]; then
        chown www-data.www-data $WWW_ROOT/* -R
        chmod -x+X $WWW_ROOT/* -R
        exit 0
      fi

      echo "postinst can't find path: $WWW_ROOT!" >&2
      exit 1
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
